language: ruby
rvm:
- 2.5.3
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: GfsH46FSjTRUz8Fx5zIVq03QeJuMU2t5E6yvwPrJOJJZ2Eb+ASnqpXzvmVTt6NBc54fbiGI5kiGwWfSGZkxRIQ/utkWpscqOrCkK0G2Vjvq2E2cHsOGJaN34Bmm136mMeLgjEmODMZQ8r7LdgL5Ie28Em4k8sLG1rT7bEmhAQGZveDBVj8bl6TYGfJZCX2r8vKOmDPm09DHaO0Pkb6plYXEC7zZXUIda2NU9npxTF++8kQjryWnKlWqJ+SA/BttOe4/DEP9SxHKN8UaunSCVKPuNsypIzib4GwMa9cXzMson2L5xEIB6ky0c9VfbSAqYPnnNrUaKuzieRnyMZx1uD4tVUVElDcA/VBKBRHPSGU/snPBpsi6owsAs+e5Y03SkdXBkbGaeUqssSmC8n3eezHZvyglGgJuzOsfw2CCCKFMbq4bjjbC0RaE5qzGDqEkXwONrfG4zZWLunLyLOpBJnUdbQkfSsOPAsN3kJei4xNoT4x7D7lbMORxU8HJGgwNPTyTqvMtxIj7b50vID739vvZIUycTGU1kJiyUTdGRs6E7mVusezJMOjgu9k5JK1u1l2N9T8D/Cgm55CyKh6gIiKATvnIufvCJI4kX2P7FSrqKgCEmdlvmm/uXLJSMV9E7GNwq1cxb2jTgOF+eNO1tWrS5csu6quMAsNswmD97zzA=
